import { QueryIntentResolverType } from "./suggestionModeClassifier";

export interface ClarificationQuestion {
  key: string;
  question: string;
}

export interface ContextPayload {
  framework: string;
  language: string;
  databaseRequired: boolean;
  idea: string;
}

export interface IntentResult {
  fullIntent: boolean;
  questions?: ClarificationQuestion[]; // Questions to ask the user for clarification if full intent is false
  contextPayload?: ContextPayload; // Payload to build context if full intent is true
  contextContent?: string; // Full TOON context generated by the AI (written to sandbox)
}

export interface ImageRef {
  mimeType: string;
  base64Data: string;
}

export interface AIProvider {
  analyzeIntent(prompt: string, userId?: string, images?: ImageRef[]): Promise<IntentResult>;
  buildContext(prompt: string, mode?: "github-import", userId?: string): Promise<string>;
  planUpdate(
    prompt: string,
    currentContext: string,
    mode?: "github-import",
    userId?: string,
  ): Promise<string>;
  generateProjectMetadata?(
    prompt: string,
    userId?: string,
    images?: ImageRef[],
  ): Promise<{ name: string; summary: string }>;
  generateCommitMessage?(prompt: string, userId?: string): Promise<string>;
  intentDetectionClassifier?(
    prompt: string,
    userId?: string,
  ): Promise<{ type: QueryIntentResolverType; data?: string[] | { status: string; suggestions?: string[]; clarificationQuestions?: string[] } }>;
}

export type ProviderType = "openai" | "gemini" | "groq" | "qwen" | "anthropic";
export interface IntentDetection {
  type: QueryIntentResolverType;
  data?: string[] | { status: string; suggestions?: string[]; clarificationQuestions?: string[] };
}
