import type { Sandbox } from "@e2b/code-interpreter";

const TYPOGRAPHY_KEBAB: Record<string, string> = {
  fontFamily: "font-family",
  fontSize: "font-size",
  fontWeight: "font-weight",
  fontStyle: "font-style",
  lineHeight: "line-height",
  letterSpacing: "letter-spacing",
  textAlign: "text-align",
  textTransform: "text-transform",
  textDecorationLine: "text-decoration-line",
  color: "color",
  backgroundColor: "background-color",
  borderColor: "border-color",
  borderStyle: "border-style",
  borderWidth: "border-width",
  borderRadius: "border-radius",
  opacity: "opacity",
  boxShadow: "box-shadow",
  marginTop: "margin-top",
  marginRight: "margin-right",
  marginBottom: "margin-bottom",
  marginLeft: "margin-left",
  paddingTop: "padding-top",
  paddingRight: "padding-right",
  paddingBottom: "padding-bottom",
  paddingLeft: "padding-left",
};

const TYPOGRAPHY_KEYS = Object.keys(TYPOGRAPHY_KEBAB);

const VALUE_PATTERN = /^[a-zA-Z0-9_\-.,#%/'"\s()]+$/;
const MAX_VALUE_LEN = 200;

const OVERRIDES_HEADER =
  "/* Auto-generated by Prettiflow Inspector. Edits will be overwritten when you Apply again. */\n";

const ROOT_LAYOUT_CANDIDATES = [
  "/workspace/frontend/src/app/layout.tsx",
  "/workspace/frontend/app/layout.tsx",
  "/workspace/src/app/layout.tsx",
  "/workspace/app/layout.tsx",
];

export interface TypographyOverridesInput {
  [selector: string]: { [property: string]: string } | undefined;
}

function escapeCssValue(raw: unknown): string | null {
  if (typeof raw !== "string") return null;
  const trimmed = raw.trim();
  if (trimmed.length === 0 || trimmed.length > MAX_VALUE_LEN) return null;
  if (!VALUE_PATTERN.test(trimmed)) return null;
  if (trimmed.includes("/*") || trimmed.includes("*/") || trimmed.includes(";") || trimmed.includes("{") || trimmed.includes("}")) return null;
  return trimmed;
}

function escapeSelectorForCss(selector: string): string | null {
  if (typeof selector !== "string") return null;
  if (selector.length === 0 || selector.length > 500) return null;
  if (selector.includes("{") || selector.includes("}") || selector.includes("/*") || selector.includes("*/")) return null;
  return selector;
}

export function buildOverridesCss(overrides: TypographyOverridesInput): string {
  const blocks: string[] = [OVERRIDES_HEADER];
  for (const [selector, style] of Object.entries(overrides)) {
    if (!style) continue;
    const safeSel = escapeSelectorForCss(selector);
    if (!safeSel) continue;
    const decls: string[] = [];
    for (const [prop, value] of Object.entries(style)) {
      if (!TYPOGRAPHY_KEYS.includes(prop)) continue;
      const safeVal = escapeCssValue(value);
      if (!safeVal) continue;
      decls.push(`  ${TYPOGRAPHY_KEBAB[prop]}: ${safeVal};`);
    }
    if (decls.length === 0) continue;
    blocks.push(`${safeSel} {\n${decls.join("\n")}\n}\n`);
  }
  return blocks.join("\n");
}

async function pathExistsInSandbox(sandbox: Sandbox, p: string): Promise<boolean> {
  try {
    await sandbox.files.read(p);
    return true;
  } catch {
    return false;
  }
}

async function findFirstExisting(sandbox: Sandbox, candidates: string[]): Promise<string | null> {
  for (const c of candidates) {
    if (await pathExistsInSandbox(sandbox, c)) return c;
  }
  return null;
}

function resolveOverridesPath(layoutPath: string): { cssPath: string; importSpec: string } {
  // Place CSS file alongside the layout so a relative import is unambiguous.
  const lastSlash = layoutPath.lastIndexOf("/");
  const dir = layoutPath.slice(0, lastSlash);
  return {
    cssPath: `${dir}/prettiflow-overrides.css`,
    importSpec: "./prettiflow-overrides.css",
  };
}

function ensureImportLine(layoutSource: string, importSpec: string): string | null {
  const importLine = `import "${importSpec}";`;
  if (layoutSource.includes(importSpec)) return null; // already imported, no-op
  // Insert after the last existing import statement; fall back to top of file.
  const lines = layoutSource.split("\n");
  let lastImportIdx = -1;
  for (let i = 0; i < lines.length; i += 1) {
    const trimmed = lines[i].trim();
    if (trimmed.startsWith("import ")) lastImportIdx = i;
  }
  if (lastImportIdx === -1) return `${importLine}\n${layoutSource}`;
  const next = [
    ...lines.slice(0, lastImportIdx + 1),
    importLine,
    ...lines.slice(lastImportIdx + 1),
  ];
  return next.join("\n");
}

export async function persistTypographyOverrides(
  sandbox: Sandbox,
  overrides: TypographyOverridesInput,
): Promise<{ cssPath: string; layoutPath: string | null; ruleCount: number }> {
  const layoutPath = await findFirstExisting(sandbox, ROOT_LAYOUT_CANDIDATES);
  if (!layoutPath) {
    throw new Error("Couldn't find the project's root layout");
  }
  const { cssPath, importSpec } = resolveOverridesPath(layoutPath);
  const css = buildOverridesCss(overrides);
  const ruleCount = (css.match(/^\S[^{]*\{/gm) || []).length;
  await sandbox.files.write(cssPath, css);
  const layoutSource = await sandbox.files.read(layoutPath);
  const next = ensureImportLine(layoutSource, importSpec);
  if (next !== null) {
    await sandbox.files.write(layoutPath, next);
  }
  return { cssPath, layoutPath, ruleCount };
}

